# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link_01
  pid: {p: 10000, i: 200, d: 1000}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_01__link_02
  pid: {p: 20000, i: 400, d: 2000}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_02__link_03
  pid: {p: 10000, i: 200, d: 1000}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_03__link_04
  pid: {p: 10000, i: 200, d: 1000}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_04__link_05
  pid: {p: 5000, i: 100, d: 500}

joint11_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link_11
  pid: {p: 10000, i: 200, d: 1000}
joint12_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_11__link_12
  pid: {p: 20000, i: 400, d: 2000}
joint13_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_12__link_13
  pid: {p: 10000, i: 200, d: 1000}
joint14_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_13__link_14
  pid: {p: 10000, i: 200, d: 1000}
joint15_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_14__link_15
  pid: {p: 5000, i: 100, d: 500}

